In [4]:
## Definindo caminho para as bases
path = r"C:\Users\andre\Desktop\FACULDADE\2022.2 ÚLTIMO\BIgData\Projeto\Crimes in UK"
print(path)

C:\Users\andre\Desktop\FACULDADE\2022.2 ÚLTIMO\BIgData\Projeto\Crimes in UK

In [12]:
## Observando a versão do Dask
!pip show dask

Name: dask
Version: 2022.2.1
Summary: Parallel PyData with Task Scheduling
Home-page: https://github.com/dask/dask/
Author:
Author-email:
License: BSD
Location: c:\users\andre\anaconda3\lib\site-packages
Requires: cloudpickle, fsspec, packaging, partd, pyyaml, toolz
Required-by: datashader, distributed, intake

In [13]:
# Para utilizar recursos do sistema
import os
import sys

# Bibliotecas DASK
import dask
from dask.distributed import Client
import dask.dataframe as dd # similar ao pandas
import dask.multiprocessing

# Para plot
%matplotlib inline
import matplotlib.pyplot as plt

In [14]:
print('Executável:')
print(sys.executable)

print('\nVersão do Python:')
print(sys.version)

Executável:
C:\Users\andre\anaconda3\python.exe

Versão do Python:
3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]

In [15]:
## Definindo os clusters
client = Client(n_workers=4, threads_per_worker=1, memory_limit='1GB')

In [16]:
client

In [35]:
## Trazendo 3 bases para observação inicial, as bases são referentes à mesma localização mas com
## informações diferentes
metro_outcomes = dd.read_csv(f"{path}\\metropolitan-outcomes.csv")
metro_sas = dd.read_csv(f"{path}\\metropolitan-stop-and-search.csv")
metro_street = dd.read_csv(f"{path}\\metropolitan-street.csv")

In [36]:
metro_outcomes.tail()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
293602,77e2ea6be9266ddbf76ddfd5ff09b6a06a1e190f931388...,2022-02,Metropolitan Police Service,Metropolitan Police Service,-0.059500,51.667785,On or near WORCESTERS AVENUE,E01001410,Enfield 005C,Investigation complete; no suspect identified
293603,d127aa5fb0d3851edd7bad23a0ba09b20db0697cf107fd...,2022-02,Metropolitan Police Service,Metropolitan Police Service,-0.076231,51.651748,On or near Parking Area,E01001512,Enfield 015D,Investigation complete; no suspect identified
293604,17f40817c172f2caab47952127f75cdbebe5645f50c079...,2022-02,Metropolitan Police Service,Metropolitan Police Service,-0.087202,51.608162,On or near MAYFAIR GARDENS,E01002091,Haringey 006A,Investigation complete; no suspect identified
293605,a0e9343c352bc36c35dcedf8810f4fa49b08aa9fb6485c...,2022-02,Metropolitan Police Service,Metropolitan Police Service,-0.127942,51.630661,On or near HIGH STREET,E01001519,Enfield 020D,Investigation complete; no suspect identified
293606,36058772908c3c515645d39aace0c7377b27205d08b83d...,2022-02,Metropolitan Police Service,Metropolitan Police Service,-0.056667,51.633279,On or near WATER LANE,E01001479,Enfield 023A,Investigation complete; no suspect identified

In [37]:
metro_sas.tail()

,Type,Date,Part of a policing operation,Policing operation,Latitude,Longitude,Gender,Age range,Self-defined ethnicity,Officer-defined ethnicity,Legislation,Object of search,Outcome,Outcome linked to object of search,Removal of more than just outer clothing
406474,Person search,2022-02-28T23:47:00+00:00,False,NaN,51.533295,0.030731,Male,NaN,Black/African/Caribbean/Black British - African,Black,Misuse of Drugs Act 1971 (section 23),Controlled drugs,A no further action disposal,NaN,NaN
406475,Person search,2022-02-28T23:49:00+00:00,False,NaN,51.491231,-0.141971,Male,18-24,Asian/Asian British - Any other Asian background,Asian,Misuse of Drugs Act 1971 (section 23),Controlled drugs,Community resolution,NaN,NaN
406476,Person search,2022-02-28T23:49:00+00:00,False,NaN,51.533295,0.030731,Male,NaN,Black/African/Caribbean/Black British - African,Black,Misuse of Drugs Act 1971 (section 23),Controlled drugs,A no further action disposal,NaN,NaN
406477,Person and Vehicle search,2022-02-28T23:54:00+00:00,False,NaN,51.432683,-0.117358,Female,25-34,Other ethnic group - Not stated,Black,Misuse of Drugs Act 1971 (section 23),Controlled drugs,A no further action disposal,NaN,NaN
406478,Person and Vehicle search,2022-02-28T23:55:00+00:00,False,NaN,51.432683,-0.117358,Male,NaN,Black/African/Caribbean/Black British - Any ot...,Black,Misuse of Drugs Act 1971 (section 23),Controlled drugs,A no further action disposal,NaN,NaN

In [38]:
metro_street.tail()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
300495,7489141f0b1e66061ba502fea713ef041b5f0b98b0ed51...,2022-02,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN
300496,1a0081408e088d0ae813855e565a909d2bf814d0b88d3e...,2022-02,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN
300497,5f32be16c45d6746f1299fe486e5727808b72eee47179c...,2022-02,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Investigation complete; no suspect identified,NaN
300498,9715eb632a7260b5103f8a7d8e1ae61832d3bcf83368dd...,2022-02,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN
300499,70012e405cd9ef652d2a3398a8055f6560bc4675eb1330...,2022-02,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN

In [39]:
metro_outcomes.dtypes

Crime ID         object
Month            object
Reported by      object
Falls within     object
Longitude       float64
Latitude        float64
Location         object
LSOA code        object
LSOA name        object
Outcome type     object
dtype: object

In [40]:
metro_sas.dtypes

Type                                         object
Date                                         object
Part of a policing operation                   bool
Policing operation                          float64
Latitude                                    float64
Longitude                                   float64
Gender                                       object
Age range                                    object
Self-defined ethnicity                       object
Officer-defined ethnicity                    object
Legislation                                  object
Object of search                             object
Outcome                                      object
Outcome linked to object of search          float64
Removal of more than just outer clothing    float64
dtype: object

In [41]:
metro_street.dtypes

Crime ID                  object
Month                     object
Reported by               object
Falls within              object
Longitude                float64
Latitude                 float64
Location                  object
LSOA code                 object
LSOA name                 object
Crime type                object
Last outcome category     object
Context                  float64
dtype: object

In [42]:
freq_resul = metro_outcomes['Outcome type'].value_counts().compute()
freq_resul

Investigation complete; no suspect identified    1495781
Suspect charged                                   135554
Local resolution                                   88293
Offender given penalty notice                      20496
Offender given a caution                           20444
Offender given a drugs possession warning           1587
Offender fined                                       705
Offender sent to prison                              684
Offender given community sentence                    662
Court case unable to proceed                         303
Offender given conditional discharge                 275
Suspect charged as part of another case              252
Defendant found not guilty                           238
Offender given suspended prison sentence             220
Defendant sent to Crown Court                        108
Offender deprived of property                         81
Formal action is not in the public interest           66
Offender otherwise dealt with                         63
Offender ordered to pay compensation                  50
Unable to prosecute suspect                           19
Offender given absolute discharge                      5
Name: Outcome type, dtype: int64

In [44]:
## Trazendo outras 3 bases para observar se as colunas batem com as colunas das bases dos mesmos 
## assuntos importadas anteriormente
west_york_outcomes = dd.read_csv(f"{path}\\west-yorkshire-outcomes.csv")
west_york_sas = dd.read_csv(f"{path}\\west-yorkshire-stop-and-search.csv")
west_york_street = dd.read_csv(f"{path}\\west-yorkshire-street.csv")

In [45]:
west_york_outcomes.tail()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
398543,67de21aa6b1bf813a7fae676d64e63f59a5992e26768a6...,2022-02,West Yorkshire Police,West Yorkshire Police,-1.676957,53.684940,On or near NORTHORPE COURT,E01011142,Kirklees 020B,Suspect charged
398544,64eeac05e5d92c545a6ce7686efaa7fd2e1e849b0479d3...,2022-02,West Yorkshire Police,West Yorkshire Police,-1.541457,53.797982,On or near Shopping Area,E01033010,Leeds 111B,Local resolution
398545,bb7221911ad347d95aed8ea1fda63ce0bc62e3ec2fe574...,2022-02,West Yorkshire Police,West Yorkshire Police,-1.818117,53.558350,On or near MOSS EDGE VIEW,E01011182,Kirklees 058B,Local resolution
398546,9cac13b4430f464b30d1e765eebf6495d183edd5ab908d...,2022-02,West Yorkshire Police,West Yorkshire Police,-1.780100,53.576892,On or near BRAMBLE BANK,E01011187,Kirklees 059F,Local resolution
398547,6a49f34a79160b56c2344b5b57f04b43ca93b4f0fd486c...,2022-02,West Yorkshire Police,West Yorkshire Police,-1.780100,53.576892,On or near BRAMBLE BANK,E01011187,Kirklees 059F,Local resolution

In [46]:
west_york_sas.tail()

,Type,Date,Part of a policing operation,Policing operation,Latitude,Longitude,Gender,Age range,Self-defined ethnicity,Officer-defined ethnicity,Legislation,Object of search,Outcome,Outcome linked to object of search,Removal of more than just outer clothing
51556,Person and Vehicle search,2022-02-28T22:45:00+00:00,False,NaN,NaN,NaN,Male,25-34,Asian/Asian British - Pakistani,Asian,Misuse of Drugs Act 1971 (section 23),Controlled drugs,Arrest,False,False
51557,Person and Vehicle search,2022-02-28T23:00:00+00:00,False,NaN,53.746067,-1.635988,Male,over 34,White - English/Welsh/Scottish/Northern Irish/...,White,Misuse of Drugs Act 1971 (section 23),Controlled drugs,Community resolution,False,False
51558,Person search,2022-02-28T23:10:00+00:00,False,NaN,53.700790,-1.416581,Male,10-17,White - English/Welsh/Scottish/Northern Irish/...,White,Misuse of Drugs Act 1971 (section 23),Controlled drugs,A no further action disposal,False,True
51559,Person search,2022-02-28T23:30:00+00:00,False,NaN,53.718465,-1.891694,Male,25-34,Asian/Asian British - Pakistani,Asian,Misuse of Drugs Act 1971 (section 23),Controlled drugs,A no further action disposal,False,False
51560,Person and Vehicle search,2022-02-28T23:42:00+00:00,False,NaN,53.718465,-1.891694,Male,25-34,Asian/Asian British - Pakistani,Asian,Misuse of Drugs Act 1971 (section 23),Controlled drugs,Arrest,True,False

In [47]:
west_york_street.tail()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
321398,28d3b366feb2f0d5eef79b1bc4485e78be8e6135b5be98...,2022-02,West Yorkshire Police,West Yorkshire Police,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN
321399,af5e77971b1ea6fa74341f4b58207e5c8e063b7a00fc3e...,2022-02,West Yorkshire Police,West Yorkshire Police,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN
321400,da5ee98200d4c3ab3592ae87157ea658a60fdabeed1428...,2022-02,West Yorkshire Police,West Yorkshire Police,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN
321401,848013e744fa11b0d7e8eaa051d5423e6e93e805d93674...,2022-02,West Yorkshire Police,West Yorkshire Police,NaN,NaN,No Location,NaN,NaN,Other crime,Investigation complete; no suspect identified,NaN
321402,1b4d6c84d668cf10a6c873d689d4324008446855a4b3aa...,2022-02,West Yorkshire Police,West Yorkshire Police,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN

In [48]:
## Lista com os arquivos na pasta de importação
files = os.listdir(path)
files

['avon-and-somerset-outcomes.csv',
 'avon-and-somerset-stop-and-search.csv',
 'avon-and-somerset-street.csv',
 'bedfordshire-outcomes.csv',
 'bedfordshire-stop-and-search.csv',
 'bedfordshire-street.csv',
 'btp-stop-and-search.csv',
 'btp-street.csv',
 'cambridgeshire-outcomes.csv',
 'cambridgeshire-stop-and-search.csv',
 'cambridgeshire-street.csv',
 'cheshire-outcomes.csv',
 'cheshire-stop-and-search.csv',
 'cheshire-street.csv',
 'city-of-london-outcomes.csv',
 'city-of-london-stop-and-search.csv',
 'city-of-london-street.csv',
 'cleveland-outcomes.csv',
 'cleveland-stop-and-search.csv',
 'cleveland-street.csv',
 'cumbria-outcomes.csv',
 'cumbria-stop-and-search.csv',
 'cumbria-street.csv',
 'derbyshire-outcomes.csv',
 'derbyshire-stop-and-search.csv',
 'derbyshire-street.csv',
 'devon-and-cornwall-outcomes.csv',
 'devon-and-cornwall-stop-and-search.csv',
 'devon-and-cornwall-street.csv',
 'dorset-outcomes.csv',
 'dorset-stop-and-search.csv',
 'dorset-street.csv',
 'durham-outcomes.csv',
 'durham-stop-and-search.csv',
 'durham-street.csv',
 'dyfed-powys-outcomes.csv',
 'dyfed-powys-stop-and-search.csv',
 'dyfed-powys-street.csv',
 'essex-outcomes.csv',
 'essex-stop-and-search.csv',
 'essex-street.csv',
 'gloucestershire-outcomes.csv',
 'gloucestershire-stop-and-search.csv',
 'gloucestershire-street.csv',
 'greater-manchester-outcomes.csv',
 'greater-manchester-stop-and-search.csv',
 'greater-manchester-street.csv',
 'gwent-outcomes.csv',
 'gwent-stop-and-search.csv',
 'gwent-street.csv',
 'hampshire-outcomes.csv',
 'hampshire-stop-and-search.csv',
 'hampshire-street.csv',
 'hertfordshire-outcomes.csv',
 'hertfordshire-stop-and-search.csv',
 'hertfordshire-street.csv',
 'humberside-outcomes.csv',
 'humberside-stop-and-search.csv',
 'humberside-street.csv',
 'kent-outcomes.csv',
 'kent-stop-and-search.csv',
 'kent-street.csv',
 'lancashire-outcomes.csv',
 'lancashire-stop-and-search.csv',
 'lancashire-street.csv',
 'leicestershire-outcomes.csv',
 'leicestershire-stop-and-search.csv',
 'lincolnshire-street.csv',
 'merseyside-outcomes.csv',
 'merseyside-stop-and-search.csv',
 'merseyside-street.csv',
 'metropolitan-outcomes.csv',
 'metropolitan-stop-and-search.csv',
 'metropolitan-street.csv',
 'norfolk-outcomes.csv',
 'norfolk-stop-and-search.csv',
 'norfolk-street.csv',
 'north-wales-outcomes.csv',
 'north-wales-stop-and-search.csv',
 'north-wales-street.csv',
 'north-yorkshire-outcomes.csv',
 'north-yorkshire-stop-and-search.csv',
 'north-yorkshire-street.csv',
 'northamptonshire-outcomes.csv',
 'northamptonshire-stop-and-search.csv',
 'northamptonshire-street.csv',
 'northern-ireland-street.csv',
 'northumbria-outcomes.csv',
 'northumbria-stop-and-search.csv',
 'northumbria-street.csv',
 'nottinghamshire-outcomes.csv',
 'nottinghamshire-stop-and-search.csv',
 'nottinghamshire-street.csv',
 'south-wales-outcomes.csv',
 'south-wales-stop-and-search.csv',
 'south-wales-street.csv',
 'south-yorkshire-outcomes.csv',
 'south-yorkshire-stop-and-search.csv',
 'south-yorkshire-street.csv',
 'staffordshire-outcomes.csv',
 'staffordshire-stop-and-search.csv',
 'staffordshire-street.csv',
 'suffolk-outcomes.csv',
 'suffolk-stop-and-search.csv',
 'suffolk-street.csv',
 'surrey-outcomes.csv',
 'surrey-stop-and-search.csv',
 'surrey-street.csv',
 'sussex-outcomes.csv',
 'sussex-stop-and-search.csv',
 'sussex-street.csv',
 'thames-valley-outcomes.csv',
 'thames-valley-stop-and-search.csv',
 'thames-valley-street.csv',
 'warwickshire-outcomes.csv',
 'warwickshire-stop-and-search.csv',
 'warwickshire-street.csv',
 'west-mercia-outcomes.csv',
 'west-mercia-stop-and-search.csv',
 'west-mercia-street.csv',
 'west-midlands-outcomes.csv',
 'west-midlands-stop-and-search.csv',
 'west-midlands-street.csv',
 'west-yorkshire-outcomes.csv',
 'west-yorkshire-stop-and-search.csv',
 'west-yorkshire-street.csv',
 'wiltshire-outcomes.csv',
 'wiltshire-stop-and-search.csv',
 'wiltshire-street.csv']

In [51]:
path_outcomes = r"C:\Users\andre\Desktop\FACULDADE\2022.2 ÚLTIMO\BIgData\Projeto\Crimes in UK\Outcomes"
path_street = r"C:\Users\andre\Desktop\FACULDADE\2022.2 ÚLTIMO\BIgData\Projeto\Crimes in UK\Street"
path_stse = r"C:\Users\andre\Desktop\FACULDADE\2022.2 ÚLTIMO\BIgData\Projeto\Crimes in UK\StopAndSearch"

In [52]:
files_out = os.listdir(path_outcomes)
files_out

['avon-and-somerset-outcomes.csv',
 'bedfordshire-outcomes.csv',
 'cambridgeshire-outcomes.csv',
 'cheshire-outcomes.csv',
 'city-of-london-outcomes.csv',
 'cleveland-outcomes.csv',
 'cumbria-outcomes.csv',
 'derbyshire-outcomes.csv',
 'devon-and-cornwall-outcomes.csv',
 'dorset-outcomes.csv',
 'durham-outcomes.csv',
 'dyfed-powys-outcomes.csv',
 'essex-outcomes.csv',
 'gloucestershire-outcomes.csv',
 'greater-manchester-outcomes.csv',
 'gwent-outcomes.csv',
 'hampshire-outcomes.csv',
 'hertfordshire-outcomes.csv',
 'humberside-outcomes.csv',
 'kent-outcomes.csv',
 'lancashire-outcomes.csv',
 'leicestershire-outcomes.csv',
 'merseyside-outcomes.csv',
 'metropolitan-outcomes.csv',
 'norfolk-outcomes.csv',
 'north-wales-outcomes.csv',
 'north-yorkshire-outcomes.csv',
 'northamptonshire-outcomes.csv',
 'northumbria-outcomes.csv',
 'nottinghamshire-outcomes.csv',
 'south-wales-outcomes.csv',
 'south-yorkshire-outcomes.csv',
 'staffordshire-outcomes.csv',
 'suffolk-outcomes.csv',
 'surrey-outcomes.csv',
 'sussex-outcomes.csv',
 'thames-valley-outcomes.csv',
 'warwickshire-outcomes.csv',
 'west-mercia-outcomes.csv',
 'west-midlands-outcomes.csv',
 'west-yorkshire-outcomes.csv',
 'wiltshire-outcomes.csv']

In [53]:
avon_and_somerset_outcomes = []
bedfordshire_outcomes = []
cambridgeshire_outcomes = []
cheshire_outcomes = []
city_of_london_outcomes = []
cleveland_outcomes = []
cumbria_outcomes = []
derbyshire_outcomes = []
devon_and_cornwall_outcomes = []
dorset_outcomes = []
durham_outcomes = []
dyfed_powys_outcomes = []
essex_outcomes = []
gloucestershire_outcomes = []
greater_manchester_outcomes = []
gwent_outcomes = []
hampshire_outcomes = []
hertfordshire_outcomes = []
humberside_outcomes = []
kent_outcomes = []
lancashire_outcomes = []
leicestershire_outcomes = []
merseyside_outcomes = []
metropolitan_outcomes = []
norfolk_outcomes = []
north_wales_outcomes = []
north_yorkshire_outcomes = []
northamptonshire_outcomes = []
northumbria_outcomes = []
nottinghamshire_outcomes = []
south_wales_outcomes = []
south_yorkshire_outcomes = []
staffordshire_outcomes = []
suffolk_outcomes = []
surrey_outcomes = []
sussex_outcomes = []
thames_valley_outcomes = []
warwickshire_outcomes = []
west_mercia_outcomes = []
west_midlands_outcomes = []
west_yorkshire_outcomes = []
wiltshire_outcomes = []

In [54]:
nome_dfs = [avon_and_somerset_outcomes,
            bedfordshire_outcomes,
            cambridgeshire_outcomes,
            cheshire_outcomes,
            city_of_london_outcomes,
            cleveland_outcomes,
            cumbria_outcomes,
            derbyshire_outcomes,
            devon_and_cornwall_outcomes,
            dorset_outcomes,
            durham_outcomes,
            dyfed_powys_outcomes,
            essex_outcomes,
            gloucestershire_outcomes,
            greater_manchester_outcomes,
            gwent_outcomes,
            hampshire_outcomes,
            hertfordshire_outcomes,
            humberside_outcomes,
            kent_outcomes,
            lancashire_outcomes,
            leicestershire_outcomes,
            merseyside_outcomes,
            metropolitan_outcomes,
            norfolk_outcomes,
            north_wales_outcomes,
            north_yorkshire_outcomes,
            northamptonshire_outcomes,
            northumbria_outcomes,
            nottinghamshire_outcomes,
            south_wales_outcomes,
            south_yorkshire_outcomes,
            staffordshire_outcomes,
            suffolk_outcomes,
            surrey_outcomes,
            sussex_outcomes,
            thames_valley_outcomes,
            warwickshire_outcomes,
            west_mercia_outcomes,
            west_midlands_outcomes,
            west_yorkshire_outcomes,
            wiltshire_outcomes]

In [55]:
nome_cidades = ['avon and somerset',
            'bedfordshire',
            'cambridgeshire',
            'cheshire',
            'city of london',
            'cleveland',
            'cumbria',
            'derbyshire',
            'devon and cornwall',
            'dorset',
            'durham',
            'dyfed powys',
            'essex',
            'gloucestershire',
            'greater manchester',
            'gwent',
            'hampshire',
            'hertfordshire',
            'humberside',
            'kent',
            'lancashire',
            'leicestershire',
            'merseyside',
            'metropolitan',
            'norfolk',
            'north wales',
            'north yorkshire',
            'northamptonshire',
            'northumbria',
            'nottinghamshire',
            'south wales',
            'south yorkshire',
            'staffordshire',
            'suffolk',
            'surrey',
            'sussex',
            'thames valley',
            'warwickshire',
            'west mercia',
            'west midlands',
            'west yorkshire',
            'wiltshire']

In [56]:
%%time 
## Medindo o tempo para rodar a célula (em média 20min)
## loop com as listas criadas, para cada arquivo na pasta será rodado o for, que importará o
## arquivo e colocará o nome da cidade em uma nova coluna, posteriormente os arquivos serão
## empilhados para facilitar o trabalho da dupla
for file,df,city in zip(files_out,nome_dfs,nome_cidades):
    ## Leitura do arquivo excel
    df = dd.read_csv(os.path.join(path_outcomes,file))
    ## criando coluna 'cidade" e incluindo a cidade correspondente
    df['cidade'] = city

CPU times: total: 78.1 ms
Wall time: 534 ms